// SEARCH ACTIONS

export const SEARCH_FOCUS_CHANGED = 'SEARCH FOCUS CHANGED';
export const SEARCH_SUBMITTED = 'SEARCH SUBMITTED';
export const SEARCH_KEY_PRESSED = 'SEARCH KEY PRESSED';


export const SEARCH_INPUT_BLURRED = 'SEARCH FOCUS BLURRED';
export const SEARCH_INPUT_FOCUSED = 'SEARCH INPUT FOCUSED';