// SEARCH ACTIONS

const SEARCH_FOCUS_CHANGED = 'SEARCH FOCUS CHANGED';
const SEARCH_SUBMITTED = 'SEARCH SUBMITTED';
const SEARCH_KEY_PRESSED = 'SEARCH KEY PRESSED';

export {
    SEARCH_FOCUS_CHANGED,
    SEARCH_SUBMITTED,
    SEARCH_KEY_PRESSED
};